### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ptahdunbar** [ptahdunbar/piratedunbar.com#1]
- [ ] Launch piratedunbar.com
  - [ ] Setup WordPress site on digital ocean
  - [ ] Design pages based off `twentyseventeen`
  - [ ] Complete `v1.0.0-alpha` of `WPF/theme-starter-kit`
  - [ ] Gather content and images for landing page
